name: Deploy to GitHub Pages

on:
  schedule:
    # 每月1-7号每天10点运行一次
    - cron: "0 2 1-7 * *" # 10 AM China Standard Time (CST, UTC+8)
    # 每周二和周五运行一次
    - cron: "0 2 * * 2,5" # 10 AM China Standard Time (CST, UTC+8)
  push:
    branches: [master, test]
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Prepare public directory
        run: |
          mkdir -p public
          echo szlcsc-help.xiaowine.cc > public/CNAME

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch coupon data
        run: pnpm fetch

      - name: Build Vue project
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
